### ISSUE TITLE
Installer Issue

### ISSUE THREAD

**Issue by ChrisBaines** [ChrisBaines/DoveForums#3]
The installer fails to connect on a web server, Throwing the error Access Denied.

Working on this issue.

Everything works fine on localhost.

**Comment by Ragash** [comment]
ok it's not a "bug" it's a "security feature" :smile: 
i'm assuming you are using Cpanel (at last im using it and i occoured into the same problem).

That's caused by the newly inputted user have not the privileges on the server to create database and specifically in Cpanel you cannot assign to a database user to "create database" privileges, but simply assign the user to a Db already created.
im trying to figure out a workaroud for it but it seems easier to simply set up the Db manually with a .sql file as early repo...

**Comment by Ragash** [comment]
ok, maybe it's not what you wanted to do at the begining, but this may work in locaholst and webserver both.

just create the database from the Cpanel/Database Mysql panel, and then change the create database method to "select database". it will search and find for a given name, retouring an error if db name given is not found. Then goes directly to the creation tables method as intended.

you will jump a step, but you will mantain the possibility to choose which name use for a Db :+1:

**Comment by ChrisBaines** [comment]
Hi Ragash,

Im trying to figure out a work around myself atm, I understand what your saying regarding just inputting the user info after you use Cpanel, but some users may not know how to do this.  Hence why i have done the installer the way I have.

Ill keep you posted if I figure out a work around.

**Comment by ChrisBaines** [comment]
Pushed a update that includes Ragash's updates and modified the install file to save having to edit the database.php file directly.
